### PR TITLE
api unit test

### PR DESCRIPTION
**Pull request by MostafaHassan0**
the unit test tests the methods of the api to make sure that they are being called at the right locations.

### CODE REVIEW

**Review by FrancoMimir — APPROVED** [review]

**Review by FrancoMimir — COMMENTED** [review]
Doesn't seem to run with CI

**Comment by FrancoMimir** [comment]
Build never completes

**Review by FrancoMimir — APPROVED** [review]

**Review by FrancoMimir — APPROVED** [review]
Approving in case this miraculously gets fixed in time for the deadline.

**Review by JeanNaima — APPROVED** [review]
Still does not run but will merge for now.

**Pull request closed without merging**
